
SELECT
    TRSACTION:CUSTOMER_ID::STRING AS CUSTOMER_ID,
    TRSACTION:DATE_OF_SESSION::TIMESTAMP_NTZ AS DATE_OF_SESSION,
    VALUE:PRODUCT_ID::STRING AS PRODUCT_ID,
    VALUE:PRICE::NUMBER AS PRICE,
    'ALL_TRANSACTIONS' AS RECORD_SOURCE,
    LOAD_DATETIME

  FROM
   {{source('AUTOVAULT_PUBLIC', 'TRANSACTIONS_V1_JSON')}}, LATERAL FLATTEN(INPUT => TRSACTION:PRODUCTS_VIEWED)
