repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: check-yaml
        args: ['--unsafe']
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^generate_raw_vault/app/templates
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.9
