
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'autovault'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  hash: SHA
  max_datetime: '9999-12-31 23:59:59.999999'

quoting:
  database: false
  schema: false
  identifier: false

models:
  +transient: false
  raw_vault:
      stages:
        materialized: view

seeds:
  +enabled: true
  +database: AUTOVAULT
  +schema: PUBLIC
  autovault:
    customers_v0_1_0:
      +column_types:
        LOAD_DATETIME: TIMESTAMP_TZ(9)
    customers_v0_1_1:
      +column_types:
        LOAD_DATETIME: TIMESTAMP_TZ(9)
    products_v0_1_0:
      +column_types:
        LOAD_DATETIME: TIMESTAMP_TZ(9)
    transactions_v0_1_0:
      +column_types:
        LOAD_DATETIME: TIMESTAMP_TZ(9)
        DATE_OF_SESSION: TIMESTAMP_TZ(9)
    customer_visits_v0_1_0:
      +column_types:
        LOAD_DATETIME: TIMESTAMP_TZ(9)
