CREATE TABLE "AUTOVAULT"."PUBLIC"."CUSTOMERS_V1" (
    "CUSTOMER_ID" STRING,
    "PRODUCT_ID" STRING,
    "AVG_MONTHLY_VISITS" STRING,
    "sat1_col3" STRING,
    "sat2_col2" STRING,
    "sat3_col2" STRING,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    )
