CREATE TABLE "AUTOVAULT"."PUBLIC"."CUSTOMERS_V1" (
    "CUSTOMER_ID" STRING,
    "sat3_key" STRING,
    "AVG_MONTHLY_VISITS" STRING,
    "sat1_col2" STRING,
    "sat2_col1" STRING,
    "sat3_col1" STRING,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    )
