CREATE TABLE IF NOT EXISTS "AUTOVAULT"."PUBLIC"."CUSTOMER_PURCHASE_HISTORY_V0_2_0" (
    "CUSTOMER_ID" STRING,
    "PRODUCT_ID" STRING,
    "PRICE" NUMBER,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    );
