CREATE TABLE "AUTOVAULT"."PUBLIC"."CUSTOMERS_V0_1_0" (
    "CUSTOMER_ID" STRING,
    "AGE" STRING,
    "COUNTRY" STRING,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    );
GRANT SELECT ON "AUTOVAULT"."PUBLIC"."CUSTOMERS_V0_1_0" TO ROLE data_analyst;
GRANT SELECT ON "AUTOVAULT"."PUBLIC"."CUSTOMERS_V0_1_0" TO ROLE data_scientist;
