CREATE TABLE IF NOT EXISTS "AUTOVAULT"."PUBLIC"."PRODUCTS_V0_1_0" (
    "PRODUCT_ID" STRING,
    "MAKE" STRING,
    "MODEL" STRING,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    );
