CREATE TABLE "AUTOVAULT"."PUBLIC"."TRANSACTIONS_V1" (
    "PRODUCT_ID" STRING,
    "CUSTOMER_ID" STRING,
    "PRICE" STRING,
    "DATE_OF_SESSION" STRING,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    );
