CREATE TABLE "AUTOVAULT"."PUBLIC"."TRANSACTIONS_V1" (
    "CUSTOMER_ID" STRING,
    "DATE_OF_SESSION" TIMESTAMP_TZ(9),
    "PRODUCT_ID" STRING,
    "DATE_OF_SESSION" STRING,
    "PRICE" INT,
    "RECORD_SOURCE" STRING,
    "LOAD_DATETIME" TIMESTAMP_TZ
    );
