name: 'dbt-compile-and-docs-generate'

on:
  push:
    paths:
      - 'models/**'
      - 'dbt_project.yml'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v2

    - name: cache-python-requirements
      uses: actions/cache@v2
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip

    - name: install-python-requirements
      run: |
        pip3 install --requirement requirements.txt

    - name: compile-dbt-models
      run: |
        dbt compile

    - name: generate-dbt-docs
      run: |
        dbt docs generate
