name: 'run-linting'

on:
  push:
    paths:
      - 'generate_raw_vault/**'
  workflow_dispatch:

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v2

    - name: cache-python-requirements
      uses: actions/cache@v2
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip

    - name: install-python-requirements
      run: |
        pip3 install --requirement requirements.txt

    - name: lint-python
      run: |
        python3 -m black generate_raw_vault
