version: 2

sources:
  - name: AUTOVAULT_PUBLIC
    database: AUTOVAULT
    schema: PUBLIC
    tables:
      - name: CUSTOMERS_V0_1_0
        columns:
          - name: CUSTOMER_ID
            description: "CUSTOMERS_V1 Business key 11111"
            tests:
              - unique
              - not_null
      - name: CUSTOMERS_V0_1_1
        columns:
          - name: CUSTOMER_ID
            description: "CUSTOMERS_V2 Business key 22222"
            tests:
              - unique
              - not_null
      - name: CUSTOMER_VISITS_V0_1_0
        columns:
          - name: CUST_ID
            description: "CUSTOMER_VISITS_V1 Business key 1111"
            tests:
              - unique
              - not_null
      - name: PRODUCTS_V0_1_0
        columns:
          - name: PRODUCT_ID
            description: "PRODUCT_V1 Business key 11111"
            tests:
              - unique
              - not_null
      - name: TRANSACTIONS_V0_1_0
        columns:
          - name: CUSTOMER_ID
            description: "Customer IDs are concatenations of their region code and registration number"
            tests:
              - unique
          - name: PRODUCT_ID
            description: "Each product has a 12 digit UIID"
            tests:
              - not_null
          - name: DATE_OF_SESSION
            description: "The datetime at which the order was made"
            tests:
            description: "444444"
            tests:
              - not_null
          - name: CUSTOMER_ID
            description: "The datetime at which the order was made"
            tests:
            description: "444444"
            tests:
              - not_null
